name: Nightly Build

env:
  project_url: 'https://github.com/${{github.repository}}'
  nightly_manifest_url: 'https://github.com/${{github.repository}}/releases/download/nightly/system.json'
  nightly_download_url: 'https://github.com/${{github.repository}}/releases/download/nightly/system.zip'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Modify System Manifest for Nightly Build
        uses: cschleiden/replace-tokens@v1
        with:
          files: 'system.json'
        env:
          VERSION: 'nightly-${{ github.sha }}'
          URL: ${{ env.project_url }}
          MANIFEST: ${{ env.nightly_manifest_url }}
          DOWNLOAD: ${{ env.nightly_download_url }}

      - name: Install Dependencies
        run: npm ci

      - name: Build CSS
        run: npm run build:css --if-present

      - name: Build JS
        run: |
          npm run build --if-present
          mv --force public/pokeymanz.mjs pokeymanz.mjs

      - name: Create System Archive
        run: |
          zip --recurse-paths ./system.zip \
            system.json \
            README.md \
            LICENSE \
            pokeymanz.mjs \
            styles/pokeymanz.css \
            templates/ \
            lang/ \
            assets/

      - name: Update Nightly Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: 'Nightly Build'
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './system.json, ./system.zip'
          tag: 'nightly'
          body: |
            **Automated nightly build from latest main branch**

            :warning: **This is a development build and may be unstable!**

            - Commit: ${{ github.sha }}
            - Date: ${{ steps.date.outputs.date }}
            - Branch: ${{ github.ref_name }}

            Install URL: `${{ env.nightly_manifest_url }}`